### ISSUE TITLE
First working car detection ML model

### ISSUE THREAD

**Issue by KaustubhTrivedi** [2024-CMPU9010-GROUP-3/PROJECT#106]
- [x] Manually label part of dataset in label studio
- [x] Training and hyperparameter tuning of Yolov5 on our satellite images to detect the cars
- [x] Upgrade to Yolov8 and continue training and tuning
- [x] Parking detection script

**Comment by JessicaFornetti** [comment]
I'm updating it now as it's not really accurate anymore
