### ISSUE TITLE
Perform Initial System Architecture Planning

### ISSUE THREAD

**Issue by KaustubhTrivedi** [2024-CMPU9010-GROUP-3/PROJECT#2]
Plan the overall system architecture, including frontend-backend interactions, data flow, and technology stack decisions. Document the architecture for team reference.

Checklist:

- [ ] Identify system requirements
- [ ] Decide on technology stack
- [ ] Define system components and interactions
- [ ] Create system architecture diagrams
- [ ] Review architecture with the team
- [ ] Document architecture decisions

**Comment by YuanshuoDu** [comment]
Don't forget me 😁
