### ISSUE TITLE
Finalize market research survey

### ISSUE THREAD

**Issue by nanadess** [2024-CMPU9010-GROUP-3/PROJECT#81]
- [x] Review existing questions that Yuanshuo started
- [x] Set it up on Microsoft forms
- [x] Make adjustments to the questions + add branching
- [ ] Get survey approved by team members
- [ ] Send out survey

**Comment by nanadess** [comment]
I have made it on Microsoft Forms, I found Tally.so not very user friendly. Here is the link to the form, let me know if there are any changes I should make!

[Market research survey](https://forms.office.com/e/iF1z709bba)

@YuanshuoDu @ankraus

**Comment by YuanshuoDu** [comment]
I think it depends on how we distribute the survey. If our target audience is mostly civil officials, we should cater more questions to them and questions that can yield substantive results. Their habits and likes/dislikes of software are more important. I think we need to highlight the points they want most as users and features they are looking forward to. Thinking about "Could we make up in these areas?" Also we could try segmenting the audiences - if they answer say "I haven't used digital tools/applications for navigation" or answer no to requiring information on publicly available amenities, then they don't need to answer further as their subsequent answers won't be meaningful.

**Comment by nanadess** [comment]
Thank you for your input Yuanshuo. I have added branching in section 1 to segment the audience on those requiring information on publicly available information, which is what we are focusing on making accessible. Those who don't require this information in their job are transported to section 3 which inquires about their use of navigation software for personal purposes as that is our second target user.
I can definitely add more questions for our primary user (civil servants/ those who need info on public amenities), especially towards their habits with technology and likes/dislikes with software as you suggested. What do you think of the following?

### demographic
* what type of public amenities information do you usually require for your job?
* how often do you require/access this information?

### tech usage
* how comfortable are you with using digital maps or similar tools?
* would you prefer a web app or mobile app to access information on public amenities?

### functionalities
* which feature would be most useful for you in such an app? (search functionality, real-time availability, condition, cost, route planning, etc)
* is there a feature you wish was available in existing solutions but isn't?

**Comment by nanadess** [comment]
Okay I have made the changes @KaustubhTrivedi , let me know what you think!

**Comment by KaustubhTrivedi** [comment]
This looks pretty good enough to me. The questions cover mostly all the aspects of the project scope we are intending to target. @nanadess. I guess we can go ahead with this.

**Comment by nanadess** [comment]
Awesome thanks for the feedback! The next question is how we send it out? I was thinking since Saul has spoken to individuals in the public service, he could send it their way. But how should we go about it? Do you think its appropriate to email companies directly that can work in the public/private sector? Or send it to the whole TU Dublin mailing list? @KaustubhTrivedi  @YuanshuoDu @1Solon
